name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./stdext
      # Prevent to remake makefile (qmake is required for this)
      # Other option: copy 'Makefile-xxx' to 'Makefile' ('Makefile' will be always newer)
      run: echo "Makefile-x86_64-linux.Debug:;@:" | make -f Makefile-x86_64-linux.Debug staticlib -f -
